### ISSUE TITLE
Link "Vídeo channel at Educast" is returning page not found

### ISSUE THREAD

**Issue by dcgomes** [arquivo/robustify.js#4]
Open page: http://sobre.arquivo.pt/en/publications/videos/

Click on: "Vídeo channel at Educast"

You will get a "Page not found" warning from robustify.

But the link is not broken:
https://educast.fccn.pt/vod/channels/oo6w8h76i

Another issue to investigate is that the robustify message should be displayed in English when the users are on the English version of the site.

**Comment by danielbicho** [comment]
The problem is that educast server is badly configured. The SSL certificate chain is incomplete, some clients cannot verify it and estabilish the handshake. Reported to Educast Team.

Although the problem with certificate, the robustify alert message should only be prompted with deterministic return status code like a 404, displaying this message with a no deterministic return status code like 0 is wrong, it should simple do nothing.
